# Generated by Django 4.0.4 on 2022-04-16 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="read",
            field=models.BooleanField(default=False),
        ),
    ]
